server:
  port: 8001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://192.168.147.128:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.147.128

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.entities    # 所有Entity别名类所在包
  #config-location: //全局配置文件
  configuration:
    map-underscore-to-camel-case: true    #开启驼峰命名规则

logging:
  level:
    com:
      springboot:
        mapper: debug

#debug: true

