server:
  port: 80

spring:
  application:
    name: cloudali-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
service-url:
  nacos-user-service: http://cloudali-provider-payment